### ISSUE TITLE
Add "Download as PDF" button to profile pages

### ISSUE THREAD

**Issue by jackharrhy** [toobigtoignore/issf#103]
Currently the user must know that using the print dialog + saving as PDF is the only way to export the generated reports as a pdf.

Will most likely use https://parall.ax/products/jspdf to fix this.

**Comment by nint8835** [comment]
Backend PDF generation has been completed, now it is just up to @jackharrhy to add the button and to better format the PDF

**Comment by jackharrhy** [comment]
fixed in #131
