### ISSUE TITLE
Export data button on main page does not work

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#109]
**Describe the bug**
Export data button is supposed to return a zip file containing a CSV containing data belonging to the map. However, the file is hardcoded to be in a set location.

**To Reproduce**
1. Click "Export data"

**Expected behavior**
A zip file of CSV files should be downloaded.

**Comment by jackharrhy** [comment]
Working on it

**Comment by nint8835** [comment]
Resolved by PR #118
