### ISSUE TITLE
Missing fields and broken button in the Geographic Scope when creating an SSF Profile

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#11]
When creating an SSF profile, with a geographic scope of local, there are incomplete or missing fields that return errors sporadically. As well as this, the "Please Wait" button is shown at the wrong time.

**Comment by nint8835** [comment]
Broken button occurs as a result of an internal server error when attempting to tweet out that a profile was created. Suggested fix is to disable auto-tweeting functionality.

**Comment by nint8835** [comment]
Now getting javascript errors, Jack will look at.

**Comment by nint8835** [comment]
Button now works, but the page it redirects you to does not. Continued as issue #77
