### ISSUE TITLE
Further issues with Geographic Scope

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#116]
In working on Issue #89, I've discovered that there are two sides to the problem. Some code 

If you were to run the following SQL query, which renames `geographic_scope_region_id` to simply `id` you will then be able to create a record _without_ problem. However, when you then go to the visit the record, it will crash complaining that it can't find the original `geographic_scope_region_id`.

It fixes one problem but creates another. 

```PLpgSQL
ALTER TABLE geographic_scope_region
RENAME geographic_scope_region_id TO id;
```

**Note that this issue appears to consistent across any geographic_scope**

**Comment by nint8835** [comment]
Conflict between column names occurred due to form using an incorrect model, which has now been resolved.
