### ISSUE TITLE
Issues with Subsidies Legend

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#125]
There are a few issues with the legend on the Subsidies map layer.

**To Reproduce**
1. Open the choropleth layer
2. Follow along from here

**Text is cut off on the legend**
Looking at the green star see that "USD" is cut off if you view the Subsidies x 1,000,000 sub-layer. The text is also cut off on other sub-layers, so this should be fixed on all affected sub-layers.

**Values for the key/legend are broken**
Looking at the blue star in the screenshot, see that there is a category for "0-0" and "0-2." What we should see is "0", and "0-2." This happens on most of the Subsidies sub-layers, and should be fixed on all those affected.

**x 1000 000 missing commas**
Now looking at the red star, see that "x 1000 000" which is confusing, because it's  supposed to be one million, so it should read "x 1,000,000." This happens in both the Subsidies x 1,000,000 and Marine Values sub-layers, and needs to be fixed in both.

**Rounding broken in other sub-layers**
As seen in the screenshot, the rounding issue solved in #34 still exists on other subsidy sub-layers that we weren't previously aware of. It will need to be fixed on all sub-layers that it appears in.

**Screenshots**
![subsidies_onemillion](https://user-images.githubusercontent.com/5544782/50253950-c7159880-03c6-11e9-9ee1-f228f0750f2b.png)

**Comment by ecumene** [comment]
All doneroni in #165
