### ISSUE TITLE
404 (Not Found) static/issf_base/DataTables-1.10.2/media/img/sort_desc.png

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#127]
Attempting to load the table on the main page causes a couple of 404's from leaflet trying to access a file that supposedly doesn't exist. The file *does* exist, but it is under static/issf_base/DataTables-1.10.2/media/images

**Comment by jackharrhy** [comment]
This is due to https://github.com/toobigtoignore/issf/pull/122
