### ISSUE TITLE
Forms attempt to access invalid columns

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#140]
The following forms have been determined to be attempting to access columns that don't exist:

- Creating who's who: person_organization.id

**Comment by nint8835** [comment]
Issue seems to have magically resolved itself?

**Comment by nint8835** [comment]
Issue has re-appeared when creating things with regional geographic scope (this issue is *really* persistent)

**Comment by jackharrhy** [comment]
Fixed in #167

**Comment by nint8835** [comment]
Issue still persists, even after #167

**Comment by nint8835** [comment]
I *believe* I have managed to solve this issue by renaming the column of the db (`geographic_scope_region_country.geographic_scope_region_country_id` -> `geographic_scope_region_country.id`) so that it is able to find it. This broke the site for previous occurrences of the issue, but it appears to be working in this case.
