### ISSUE TITLE
Reimagine "Show/Hide all layers" functionality

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#146]
Throw it out the window. We've been instructed to start again and reimplement this feature in a way that is user friendly and makes sense from a UX perspective. 

Apparently the UX of the current Show/Hide button was tested amongst a group of people, and none of them guessed/intuitively knew that the Show/Hide button existed, or that that is what the button did. 

Re-implement and redesign as you see fit.

**Comment by jackharrhy** [comment]
*Idea:*
More real estate can be made available for better-suited UI elements if the map makes use of 100% the viewport width.
![image](https://user-images.githubusercontent.com/6486417/50322628-63679a00-04b0-11e9-8b26-111dc03a8dbd.png)

**Comment by ranguli** [comment]
Combined with #162
