### ISSUE TITLE
Figure out and document how SSF Percentage Completed is calculated

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#155]
No changes or fixes are required _yet_, all we need to know is how this percentage is calculated. It then needs to be documented in the code and added to the wiki under a new section.

If we sense that it is calculated inaccurately, it might need to be changed

![how](https://user-images.githubusercontent.com/5544782/50305474-7907a000-046d-11e9-83de-816194d9633f.png)

**Comment by nint8835** [comment]
Percentage is calculated as
`(fields_filled / total_fields) * 100`
which seems like a fairly sensible method of solving.

**Comment by nint8835** [comment]
Details are added to the manual.
