### ISSUE TITLE
Twitter Feed Not Showing or Updating + Incorrect Links

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#16]
**Describe the bug**
On the main page, the Twitter feed does not consistently appear. When it does appear, often times the feed will be empty even if there are recent tweets to display.

As well as this, the URL used in the tweets that link to a given record use the old domain name, not the new, issfcloud.toobigtoignore.net domain.

**Comment by jackharrhy** [comment]
Potential issue found within console output:

https://twittercommunity.com/t/deprecating-widget-settings/102295

![image](https://user-images.githubusercontent.com/6486417/48677449-b071ec80-eb4f-11e8-9b60-fbc2c840d825.png)

**Comment by ranguli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Twitter Feed](https://trello.com/c/OX6N2i7I/3-fix-twitter-feed)

**Comment by jackharrhy** [comment]
https://github.com/toobigtoignore/issf/pull/33

**Comment by jackharrhy** [comment]
I have yet to address:
> As well as this, the URL used in the tweets that link to a given record use the old domain name, not the new, issfcloud.toobigtoignore.net domain.

**Comment by ranguli** [comment]
Remaining issue of using the old dory.creait.mun.ca URL on Twitter has been addressed in PR #57
