### ISSUE TITLE
Redesign the map sidebar to the following specification

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#162]
### 3. Experience and SSF Guidelines shouldn’t both be shades of purple.

On certain displays, based on your colour profile, these actually may look like the same colour. We should make them more visibly distinct from one another.

![whatcolouristhisdress](https://user-images.githubusercontent.com/5544782/50304521-bd457100-046a-11e9-8759-a939015381c1.png)

As well, both of their icons need to be changed. They aren't very relevant or indicative.

### 4. The sidebar icons are too big on certain displays
For example, on a 1280x1024 display the icons are too big and look a little "kiddish" 

![selection_005](https://user-images.githubusercontent.com/5544782/50305081-650f6e80-046c-11e9-91fa-cdc53bd155e9.png)

### 5. The colour of Capacity Development is the same colour as the map icon, this can be confusing.
The Capacity Development icon, is the universal symbol for fullscreen. This is not indicative of what the layer represents, and a new icon should be picked.

![colours](https://user-images.githubusercontent.com/5544782/50304714-48266b80-046b-11e9-919e-1a4024eab7d0.png)

### 6.  White on Grey Text:

Not so bad...
![capture d ecran_2018-12-20_15-13-30](https://user-images.githubusercontent.com/5544782/50304329-355f6700-046a-11e9-9b08-b625829ae442.png)
Unreadable...
![capture d ecran_2018-12-20_15-14-04](https://user-images.githubusercontent.com/5544782/50304333-37292a80-046a-11e9-8f3f-63201c901db8.png)

### 7.  Redo Show/Hide All Layers

Throw it out the window. We've been instructed to start again and reimplement this feature in a way that is user friendly and makes sense from a UX perspective. 

Apparently the UX of the current Show/Hide button was tested amongst a group of people, and none of them guessed/intuitively knew that the Show/Hide button existed, or that that is what the button did. 

Re-implement and redesign as you see fit.

More real estate can be made available for better-suited UI elements if the map makes use of 100% the viewport width.
![image](https://user-images.githubusercontent.com/6486417/50322628-63679a00-04b0-11e9-8b26-111dc03a8dbd.png)

**Comment by ranguli** [comment]
@ecumene-software not sure how we want to go about fixing this
![hmm](https://user-images.githubusercontent.com/5544782/50517715-1ecd9700-0a8c-11e9-835f-dc6ea3417ee0.png)

**Comment by ecumene** [comment]
Waiting for a PR after Jack finishes his edits

**Comment by ecumene** [comment]
Fixed in #215
