### ISSUE TITLE
New icons need to be updated in certain places

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#184]
Old icons are still shown on the map:
![oldicon1](https://user-images.githubusercontent.com/5544782/50517359-a1eded80-0a8a-11e9-86f7-fb3110ffbc14.png)

Old icons are shown (and seem to be tiled - but cut off on the top) on the "Welcome" pane on the homepage
![oldicons3](https://user-images.githubusercontent.com/5544782/50517360-a1eded80-0a8a-11e9-82e4-2c5fc540f096.png)

Old icons are shown on record pages, and the old colours are as well
![oldicons4](https://user-images.githubusercontent.com/5544782/50517361-a1eded80-0a8a-11e9-8952-0151398dd02b.png)

Old icons are shown on the contribution panes on the homepage
![oldpictures2](https://user-images.githubusercontent.com/5544782/50517362-a1eded80-0a8a-11e9-99c4-8da2da1badaa.png)

When contributing a record:
![Uploading oldicon5.png…]()

**Comment by ecumene** [comment]
Waiting for a PR after Jack finishes his edits

**Comment by ecumene** [comment]
Fixed
