### ISSUE TITLE
Records should always used a standardized date format

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#186]
If you go to /details/guidelines/3535/ you'll see an example of a user being allowed to enter a non-standard date format. In all likeliness, it should probably follow a strict ```YYYY-MM-DD``` format (or whichever is preferrable) and the forms should not accept improper date stamps.

![baddate](https://user-images.githubusercontent.com/5544782/50517515-37897d00-0a8b-11e9-8434-947bd45c8808.png)

**Comment by nint8835** [comment]
This is an issue with the cleaned database. Such a value cannot be normally entered by a user, and is a result of the following lines in the clean script for the database.

```sql
UPDATE ssf_guidelines SET
  organizer = 'Harold',
  start_year = '0000',
  start_month = '1',
  start_day = '1',
  end_month = '1',
  end_year = '0000',
  end_day = '1';
```

Forms are set to use a datefield which already have the following forms supported:

![](https://i.bootleg.technology/R5x0dApO1i.png)
