### ISSUE TITLE
Colour of the top border of map sidebar should match map border colour.

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#187]
The top tab should be changed to be the same colour as the blue map border directly to the left of it. The bottom tab probably should not exist, or be changed to the grey colour used in the bar.

![changecolour](https://user-images.githubusercontent.com/5544782/50517845-ebd7d300-0a8c-11e9-9da0-feb3185ddc3c.png)

**Comment by jackharrhy** [comment]
:open_hands: an :open_hands: issue :open_hands: for :open_hands: something :open_hands: in :open_hands: a :open_hands: non :open_hands: master :open_hands: branch :open_hands: not :open_hands: in :open_hands: its :open_hands: pr :open_hands: or :open_hands: waiting :open_hands: for :open_hands: the :open_hands: pr :open_hands: to :open_hands: be :open_hands: put :open_hands:  up

**Comment by ecumene** [comment]
Waiting for a PR after Jack finishes his edits
