### ISSUE TITLE
Always use HTTPS

### ISSUE THREAD

**Issue by jackharrhy** [toobigtoignore/issf#26]
**Describe the bug**
Some resources are loaded over `http`, so even though the site is secure, most browsers will display the security as insecure.

**Expected behavior**
All resources should be loaded over `https`

**Screenshots**
<img width="307" alt="issf__information_system_on_small-scale_fisheries" src="https://user-images.githubusercontent.com/6486417/48725240-246ecc00-ec06-11e8-813e-3075463ee8c4.png">

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by jackharrhy** [comment]
https://github.com/toobigtoignore/issf/pull/33

**Comment by ecumene** [comment]
**After a small investigation..**

- All CDNs are grabbed through HTTPS
- Database references to resources don't need to be HTTPS
- Internal files don't need to be referenced any different
- _The chrome warning is probably due to the development server being hosted without SSL_
