### ISSUE TITLE
Improve Profile UI

### ISSUE THREAD

**Issue by jackharrhy** [toobigtoignore/issf#28]
**Describe the bug**
Missing data seemingly results in useless dropdown boxes, that still drop open but reveal just more whitespace with no context.

**Expected behavior**
More context should be given to the end user to indicate that no data was found.

**Screenshots**
<img width="788" alt="issf__small-scale_fishery_profile_-_test" src="https://user-images.githubusercontent.com/6486417/48725932-4f5a1f80-ec08-11e8-8025-27fe67fb56d2.png">

**Comment by ranguli** [comment]
Will be revisted when time allows
