### ISSUE TITLE
Inland Catch value has improper rounding on subsidy layer

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#34]
**Describe the bug**
When using the subsidy map layer, the inland catch value is displayed with too many decimal points. It should be rounded, perhaps to the nearest whole number.

**To Reproduce**
1. Enable the appropriate layer (green circle in screenshot)
2. Hover over any country
3. See that the inland catch value is rounded strangely.

**Expected behavior**
The value should appear rounded to the nearest whole number

**Screenshots**

![roundsubsidies](https://user-images.githubusercontent.com/5544782/49528318-50d54a00-f88e-11e8-8020-c50c68982eeb.png)
![roundsubsidies2](https://user-images.githubusercontent.com/5544782/49529447-998e0280-f890-11e8-8a8d-eff078a0a16d.png)

**Comment by ecumene** [comment]
Fixed in #80
