### ISSUE TITLE
Subsidy Layer does not update country names properly.

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#35]
**Describe the bug**
When hovering over a country in the subsidy layer, the name of the country listed in the top right (red rectangle) does not always change, and may become 'stuck' only showing the name of the country that the user was hovering over previously.

**To Reproduce**

1. Open the subsidy layer
2. Select "Subsidies Proportion %" in the legend
2. Hover over any country, except one that has "No data" in its value
3. Now hover over a different country that has "No data" and see that the previously hovered country name is still being shown, _not_ the new country that you are currently hovering over.

**Expected behavior**
The name of the country in the top right should always show the name of the current country hovered over. If no country is being hovered over, such as hovering over the ocean, no text data should be shown and the grey rectangle containing the text should be hidden accordingly. Both the text data and the grey rectangle should then reappear with relevant information when a new country is selected.

**Screenshots**

![subsidy](https://user-images.githubusercontent.com/5544782/50252439-90894f00-03c1-11e9-955f-b165086f1ace.png)

**Comment by ranguli** [comment]
Unable to reproduce on any available OS or browser, including what it was initially reported with.

**Comment by ecumene** [comment]
Fixed in #126
