### ISSUE TITLE
TemplateSyntaxError at /accounts/profile/ 'js' is not a registered tag library.

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#70]
**Describe the bug**
When attempting to access the user details for the test user (catfish), a templatesyntaxerror occurs instead of the page loading.

**To Reproduce**
1. Log in as the test user (catfish)
2. Click "catfish" in the top right
3. Click "User Profile"

**Expected behavior**
You should see the user profile, instead of an error

**Comment by ranguli** [comment]
Duplicate issue of #59
