### ISSUE TITLE
Use gzip functionality with django to decrease load times for static files

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#74]
If we use gzip with nginx, we may be able to cache files like chorodata.geojson to improve map speed.

**Comment by jackharrhy** [comment]
@ecumene-software , is this resolved due to your branch being merged? Or does the `.geojson` -> `.json` issue also need to be resolved to fix this?

**Comment by ecumene** [comment]
> @ecumene-software the `.geojson` -> `.json` issue also need to be resolved to fix this?

Yes

**Comment by nint8835** [comment]
Resolved with PR #102
