### ISSUE TITLE
PDFs hard-coded and missing

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#79]
Currently the site depends on having pdf templates in hard-coded paths such as "/home/projects/issf/issf_prod/apps/details/static/details/pdf/ISSF_Profile_Example_Brazil.pdf", and the PDFs are not in the repo. They should be added to the repo and the code referring to them rewritten so it doesn't use a hard-coded path.

**Comment by ranguli** [comment]
Solve with PR #83
