### ISSUE TITLE
Search form on main page may be vulnerable to SQLI

### ISSUE THREAD

**Issue by nint8835** [toobigtoignore/issf#93]
There are many places in the main search form that the data the user provides is injected into the sql statement with very few modifications, checks, or distinguishing from commands (via prepared statements), leaving the server open to SQL injection.

**Comment by jackharrhy** [comment]
:worried:

**Comment by nint8835** [comment]
Search form on main page uses some sort of arcane wizardry and undocumented Django methods to perform searching, and as a result it is impossible to discern precisely what it is doing and whether or not it is vulnerable to SQL Injection. It definitely does some *strange* things when you do certain things to it, but that could be a quirk of Django or whatever is going on behind the scenes. Best course of action is to simply remove these characters from the strings.

**Comment by nint8835** [comment]
Potentially resolved by #110. Will be re-opened if that is not the case.
