### ISSUE TITLE
"Who's Who" on main page always shows same user

### ISSUE THREAD

**Issue by jackharrhy** [toobigtoignore/issf#95]
On the homepage, the "Who's Who" section always seems to be displaying "Erin Loury".

![chrome_jthrdeaaql](https://user-images.githubusercontent.com/6486417/50048965-f6b95d80-00b3-11e9-919f-992dcb5bc10f.png)

It should show other users.

**Comment by nint8835** [comment]
The who's who appears at first glance of the backend code to always display the most recent who's who posted
```python
who_feature = WhoFeature.objects.latest('id')
```

**Comment by jackharrhy** [comment]
So it's technically a _feature_ , but by the context of the div I think it should be dynamic.

**Comment by ranguli** [comment]
It's purposefully designed to be a showcase of a particular user, the expected behavior is that it should not be change - everything working as intended here.
