### ISSUE TITLE
Choropleth/Subsidy layer should read "No data" for countries with an inland catch of 0.

### ISSUE THREAD

**Issue by ranguli** [toobigtoignore/issf#98]
When a country in the subsidy/choropleth layer has an Inland Catch of 0, the text in the top right rectangle should say "No data." This makes it easily identifiable to the user that it falls into the category of "No data" seen in the legend.

**Screenshots**
![choropleth](https://user-images.githubusercontent.com/5544782/50056018-0f1b8d80-0131-11e9-8e65-cf4964133540.png)

**Comment by ecumene** [comment]
Fixed in #114
